### ISSUE TITLE
Broken macos (intel) wheel on v1.3rc1

### ISSUE THREAD

**Issue by joel-magnusson** [hi-chi/pipic#24]
Installed `pipic` on macos (intel) from binary wheel  `pipic-1.3rc1-cp312-cp312-macosx_14_0_x86_64.whl`, but running the `basic_example.py` results in the following error:
```
Traceback (most recent call last):
  File "/Users/joel/projects/pipic-test/basic_example.py", line 1, in <module>
    import pipic
  File "/Users/joel/.pyenv/versions/test_pipic_install/lib/python3.12/site-packages/pipic/__init__.py", line 6, in <module>
    import pipic.consts as consts
  File "/Users/joel/.pyenv/versions/test_pipic_install/lib/python3.12/site-packages/pipic/consts.py", line 24, in <module>
    from . import _pipic
ImportError: dlopen(/Users/joel/.pyenv/versions/test_pipic_install/lib/python3.12/site-packages/pipic/_pipic.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '___kmpc_end_serialized_parallel'
```
It was installed using:
```bash
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pipic==1.3rc1
```
and run with
```bash
python basic_example.py
```

**Comment by joel-magnusson** [comment]
Issue was at least partially fixed by #25. Now (with `1.3rc2`) the correct wheel is grabbed and it is functioning as expected.
